# Generated by Django 4.0.5 on 2022-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('tipo', models.CharField(blank=True, choices=[('PF', 'Persona Física'), ('PM', 'Persona Moral')], max_length=45, null=True)),
            ],
        ),
    ]
