# Generated by Django 4.0.5 on 2022-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('genero', models.CharField(choices=[('M', 'Mutante'), ('H', 'Humano'), ('E', 'Extraterrestre'), ('O', 'Otro')], max_length=1)),
                ('tipo', models.CharField(blank=True, choices=[('Heroe', 'Héroe'), ('Villano', 'Villano')], max_length=45, null=True)),
                ('compania', models.CharField(blank=True, choices=[('Marvel', 'Marvel'), ('DC', 'DC Comics'), ('Dark Horse', 'Dark Horse'), ('IDW', 'IDW Publishing')], max_length=45, null=True)),
            ],
        ),
    ]
