# Generated by Django 4.0.5 on 2022-08-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0003_revista_tarjeta_clientetarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloColeccionable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('compania', models.CharField(blank=True, choices=[('Marvel', 'Marvel'), ('DC', 'DC Comics'), ('Dark Horse', 'Dark Horse'), ('IDW', 'IDW Publishing')], max_length=45, null=True)),
                ('anio', models.IntegerField()),
                ('nuevo', models.IntegerField()),
                ('estado', models.CharField(blank=True, choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=45, null=True)),
            ],
        ),
    ]
