# Generated by Django 4.0.5 on 2022-08-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0004_articulocoleccionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='genero',
            field=models.CharField(choices=[('M', 'Mutante'), ('H', 'Humano'), ('E', 'Extraterrestre'), ('S', 'Super Humano'), ('O', 'Otro')], max_length=1),
        ),
    ]
