# Generated by Django 4.0.5 on 2022-08-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0005_alter_personaje_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='miembros',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='revista',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revista',
            name='serie',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='revista',
            name='titulo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='revista',
            name='volumen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revista',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='revista',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
