# Generated by Django 4.0.5 on 2022-08-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic_app', '0006_revista_miembros_revista_numero_revista_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='imagen',
            field=models.TextField(default=''),
        ),
    ]
